name: Build docker image
on:
  push:
    paths:
      - ".github/workflows/docker.yml"
      - "Makefile"
      - "Dockerfile"
      - "Dockerfile.native"
      - "src/**"
      - "project.clj"
      - "reflection.json"
      - "resources.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build -t rinx/vald-meta-backup-halodb .
    - name: login to DockerHub
      run: |
        echo ${DOCKERHUB_PASS} | docker login --username ${DOCKERHUB_USER} --password-stdin
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    - name: tag and push to DockerHub
      run: |
        docker push rinx/vald-meta-backup-halodb:latest
  build-native:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build -t rinx/vald-meta-backup-halodb-native -f Dockerfile.native .
    - name: login to DockerHub
      run: |
        echo ${DOCKERHUB_PASS} | docker login --username ${DOCKERHUB_USER} --password-stdin
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    - name: tag and push to DockerHub
      run: |
        docker push rinx/vald-meta-backup-halodb-native:latest
